In [29]:
import numpy as np
import random

In [5]:
array_1 = np.array([i for i in range(1,11)], dtype = int)
print(array_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
array_2 = np.zeros((3,3))
print(array_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
array_3 = np.array([[random.randint(1,10) for _ in range(5)] for _ in range(5)])
print(array_3)

[[10  9  9]
 [ 2  9  7]
 [ 8  1  2]]


In [21]:
array_4 = np.array([[random.uniform(0,1) for _ in range(4)] for _ in range(4)])
print(array_4)

[[0.79937704 0.39739755 0.65104414 0.85197311]
 [0.47951414 0.94630062 0.33644139 0.66028104]
 [0.8183857  0.76159761 0.81749367 0.80086631]
 [0.60562886 0.17390322 0.81712258 0.51975122]]


In [25]:
array_5_1 = np.array([random.randint(1,10) for _ in range(5)])
array_5_2 = np.array([random.randint(1,10) for _ in range(5)])
sum_arr_5 = array_5_1 + array_5_2
diff_arr_5 = array_5_1 - array_5_2
mult_arr_5 = array_5_1 * array_5_2
print(array_5_1)
print(array_5_2)
print(sum_arr_5)
print(diff_arr_5)
print(mult_arr_5)


[7 2 1 3 5]
[10  3  9 10  5]
[17  5 10 13 10]
[-3 -1 -8 -7  0]
[70  6  9 30 25]


In [26]:
array_6_1 = np.array([i for i in range(1,7)], dtype = int)
array_6_2 = np.array([i for i in range(1,7)], dtype = int)
scalar_mult = np.dot(array_6_1,array_6_2)
print(scalar_mult)

91


In [30]:
array_7_1 = np.array([[random.randint(1,10) for _ in range(2)] for _ in range(2)])
array_7_2 = np.array([[random.randint(1,10) for _ in range(3)] for _ in range(2)])
array_mult = np.dot(array_7_1,array_7_2 )
print(array_mult)

[[36 12 48]
 [54 18 72]]


In [31]:
array_8_1 = np.array([[random.randint(1,10) for _ in range(3)] for _ in range(3)])
array_inv = np.linalg.inv(array_8_1)
print(array_inv)

[[ 0.28767123 -0.02739726 -0.43835616]
 [-0.23287671  0.26027397  0.16438356]
 [ 0.16438356 -0.30136986  0.17808219]]


In [41]:
array_9_1 = np.array([[random.uniform(0,1) for _ in range(4)] for _ in range(4)])
array_trans = np.transpose(array_9_1)
print(array_9_1)
print(array_trans)


[[0.70411757 0.99810861 0.71322582 0.46894909]
 [0.90312932 0.65029337 0.31884276 0.21175335]
 [0.5473332  0.36223154 0.62151648 0.12802421]
 [0.47902368 0.79128407 0.6425913  0.98408983]]
[[0.70411757 0.90312932 0.5473332  0.47902368]
 [0.99810861 0.65029337 0.36223154 0.79128407]
 [0.71322582 0.31884276 0.62151648 0.6425913 ]
 [0.46894909 0.21175335 0.12802421 0.98408983]]


In [44]:
array_10_1 = np.array([[random.randint(1,10) for _ in range(4)] for _ in range(3)])
array_10_2 = np.array([random.randint(1,10) for _ in range(4)])
array_mult = np.dot(array_10_1,array_10_2 )
print(array_mult)

[214 144  96]


In [47]:
array_11_1 = np.array([[random.uniform(0,1) for _ in range(3)] for _ in range(2)])
array_11_2 = np.array([random.uniform(0,1) for _ in range(3)])
array_mult = np.dot(array_11_1,array_11_2 )
print(array_mult)

[0.41354435 0.81542185]


In [51]:
array_12_1 = np.array([[random.randint(1,10) for _ in range(2)] for _ in range(2)])
array_12_2 = np.array([[random.randint(1,10) for _ in range(2)] for _ in range(2)])
array_mult = array_12_1 * array_12_2
print(array_12_1)
print(array_12_2)
print(array_mult)

[[4 4]
 [8 7]]
[[4 9]
 [7 5]]
[[16 36]
 [56 35]]


In [6]:
array_13_1 = np.array([[random.randint(1,10) for _ in range(2)] for _ in range(2)])
array_13_2 = np.array([[random.randint(1,10) for _ in range(2)] for _ in range(2)])
array_mult = np.dot(array_13_1,array_13_2)
print(array_13_1)
print(array_13_2)
print(array_mult)

[[2 2]
 [9 6]]
[[4 8]
 [2 3]]
[[12 22]
 [48 90]]


In [8]:
array_14_1 = np.array([[random.randint(1,100) for _ in range(5)] for _ in range(5)])
array_sum_nums = array_14_1.sum()
print(array_14_1)
print(array_sum_nums)

[[92 64 70 84 72]
 [17 85 25 72  5]
 [74  4 30 93 16]
 [39 42 52 80 73]
 [78 45 33 62 33]]
1340


In [12]:
array_15_1 = np.array([[random.randint(1,10) for _ in range(4)] for _ in range(4)])
array_15_2 = np.array([[random.randint(1,10) for _ in range(4)] for _ in range(4)])
array_dif = array_15_1 - array_15_2
print(array_15_1)
print(array_15_2)
print(array_dif)

[[10  6  8  8]
 [ 9  2  5  3]
 [ 8  9  2  5]
 [ 9  9  5  4]]
[[4 1 9 1]
 [2 7 2 8]
 [5 8 7 6]
 [3 8 4 4]]
[[ 6  5 -1  7]
 [ 7 -5  3 -5]
 [ 3  1 -5 -1]
 [ 6  1  1  0]]


In [14]:
array_16_1 = np.array([[random.uniform(0,1) for _ in range(3)] for _ in range(3)])
array_sum_rows = np.array([sum(row) for row in array_16_1])
print(array_16_1)
print(array_sum_rows)

[[0.95392439 0.62121225 0.13962426]
 [0.55669701 0.03303308 0.92308829]
 [0.51297741 0.03868724 0.71856692]]
[1.71476089 1.51281839 1.27023157]


In [26]:
array_17_1 = np.array([[random.randint(1,10) for _ in range(3)] for _ in range(4)], dtype = int)
array_squared = np.array([[item**2 for item in row] for row in array_17_1])
print(array_17_1)
print(array_squared)

[[7 3 5]
 [7 1 5]
 [3 5 7]
 [2 7 9]]
[[49  9 25]
 [49  1 25]
 [ 9 25 49]
 [ 4 49 81]]


In [28]:
array_18_1 = np.array([random.randint(1,10) for _ in range(4)])
vector_sqrt = np.array([np.sqrt(item)for item in array_18_1])
print(array_18_1)
print(vector_sqrt)

[2 3 1 4]
[1.41421356 1.73205081 1.         2.        ]
